services:
  postgres:
    image: postgres:15-alpine
    container_name: nextjs_postgres_db
    environment:
      POSTGRES_USER: carlcad
      POSTGRES_PASSWORD: SamThoughtThereWasAnEarthquake123!
      POSTGRES_DB: WorldInteraction
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
